#!/bin/bash

sun7i="bananapi bananapipro cubieboard2 cubietruck lamobo-r1 lime2 lime2-emmc lime micro orangepi pcduino3 pcduino3nano "
sun8i="bananapim2plus beelinkx2 nanopiair nanopim1 nanopim1plus nanopineo orangepi2 orangepilite orangepione orangepipc orangepipcplus orangepiplus2e orangepiplus orangepizero "
#supported="aw-som-a20 bananapi bananapilcd7 bananapim1plus bananapim1pluslcd7 bananapim2plus bananapipro bananapiprolcd7 beelinkx2 cubieboard2 cubieboard2dual cubieboard cubietruck lamobo-r1 lime2 lime2-emmc lime-a10 lime-a10-lcd lime-a33 lime micro nanopiair nanopim1 nanopim1plus nanopineo olinux-som-a13 orangepi2 orangepi orangepilite orangepione orangepipc orangepipcplus orangepiplus2e orangepiplus orangepizero pcduino2 pcduino3 pcduino3nano "
supported="$sun8i"

for target in $supported; do
    echo -n Testing $target
    rm -fr /tmp/*.deb
    rm -fr /tmp/sunxi-boot

    (
	set -e
	cd /tmp;
	apt-get -qq download linux-jessie-root-$target linux-u-boot-$target-default
	mkdir -p /tmp/sunxi-boot
	dpkg -x /tmp/linux-jessie-root-$target*.deb /tmp/sunxi-boot/
	dpkg -x /tmp/linux-u-boot-$target*.deb /tmp/sunxi-boot/
	wget https://raw.githubusercontent.com/igorpecovnik/lib/master/config/boards/$target.conf

	touch /tmp/sunxi-boot/usr/share/armbian/boot.cmd
	touch /tmp/sunxi-boot/usr/share/armbian/armbianEnv.txt
	touch /tmp/sunxi-boot/usr/lib/linux-u-boot-$target*/u-boot-sunxi-with-spl.bin
	touch /tmp/sunxi-boot/usr/lib/u-boot/platform_install.sh
	grep MODULES= $target.conf > /dev/null
	grep LINUXFAMILY=\"sun7i\" $target.conf > /dev/null

    ) 2>/dev/null
    if [ $? -eq 0 ]; then
	echo : OK
    else
	echo : NOK
    fi
done

rm -fr /tmp/*.deb
rm -fr /tmp/sunxi-boot
